name: CI/CD

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Unit Test
        run: go test -v ./...

      - name: Doc Test
        run: |
          rm -rf doctest && mkdir -p doctest
          sed -n '16,60p' readme.md > doctest/doctest.go
          cd doctest && go run doctest.go && cat *
